defaults:
  - _self_
  - paths: example 
  - model: WizardLM70B

pathology: appendicitis
agent: ZeroShot
prompt_template: VANILLA
summarize: True
fewshot: False
include_ref_range: False
bin_lab_results: False
bin_lab_results_abnormal: False
provide_diagnostic_criteria: False
include_tool_use_examples: False
abbreviated: True
self_consistency: False
only_abnormal_labs: False

seed: 2023
local_logging: True
run_descr:

first_patient:
patient_list_path:

order: pli
diagnostic_criteria:

rr_name: RR
diag_crit_writer_openai_api_key:
confirm_diagnosis: False
save_probabilities: False

annotate_clinical: False
patient_simulator: False

vllm_base_url:

skill_path:
skill_inject: examples

# Tree of Thoughts (ToT) parameters
tot_n_generate: 10
tot_breadth: 3
tot_max_depth: 10
tot_temperature: 1.0
tot_eval_temperature: 0.0