# @package _global_
defaults:
  - _self_

openai_api_key:
model_name: "google/medgemma-1.5-4b-it"
max_context_length: 8192
exllama: False

system_tag_start: "<bos><start_of_turn>user\n"
system_tag_end: "<end_of_turn>\n"

user_tag_start: "<start_of_turn>user\n"
user_tag_end: "<end_of_turn>\n"

ai_tag_start: "<start_of_turn>model\n"
ai_tag_end: "<end_of_turn>\n"

stop_words:
 - "<end_of_turn>"
 - "<eos>"
