# @package _global_
defaults:
  - _self_

openai_api_key:
vllm_base_url: "http://localhost:8000/v1"
model_name: "Qwen/Qwen3-30B-A3B-Instruct-2507"
max_context_length: 32768
exllama: False

system_tag_start: "<|im_start|>system\n"
system_tag_end: "<|im_end|>\n"

user_tag_start: "<|im_start|>user\n"
user_tag_end: "<|im_end|>\n"

ai_tag_start: "<|im_start|>assistant\n"
ai_tag_end: "<|im_end|>\n"

stop_words:
 - "<|im_end|>"
 - "<|endoftext|>"
